run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - misspell
    - unconvert
    - gocyclo
    - goimports

issues:
  exclude-use-default: false
  max-same-issues: 0

linters-settings:
  gocyclo:
    min-complexity: 15
