# Infrastructure Services
# Reverse proxy, dashboard, authentication, transcoding

version: '3.8'

services:
  # Traefik - Reverse Proxy with SSL
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
      - "${TRAEFIK_DASHBOARD_PORT:-8083}:8080"  # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-letsencrypt:/letsencrypt
    restart: unless-stopped
    networks:
      - media-network
    profiles:
      - proxy

  # Heimdall - Application Dashboard
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/Los_Angeles}
    volumes:
      - heimdall-config:/config
    ports:
      - "${HEIMDALL_PORT:-8082}:80"
    restart: unless-stopped
    networks:
      - media-network
    profiles:
      - dashboard

  # Homepage - Alternative Dashboard
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/Los_Angeles}
    volumes:
      - homepage-config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "${HOMEPAGE_PORT:-3000}:3000"
    restart: unless-stopped
    networks:
      - media-network
    profiles:
      - dashboard-alt

  # Authentik - Authentication & SSO
  authentik-postgresql:
    image: postgres:16-alpine
    container_name: authentik-db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - authentik-database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${AUTHENTIK_PG_PASS:-changeme}
      - POSTGRES_USER=authentik
      - POSTGRES_DB=authentik
    networks:
      - media-network
    profiles:
      - auth

  authentik-redis:
    image: redis:alpine
    container_name: authentik-redis
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - authentik-redis:/data
    networks:
      - media-network
    profiles:
      - auth

  authentik-server:
    image: ghcr.io/goauthentik/server:latest
    container_name: authentik-server
    restart: unless-stopped
    command: server
    environment:
      - AUTHENTIK_REDIS__HOST=authentik-redis
      - AUTHENTIK_POSTGRESQL__HOST=authentik-postgresql
      - AUTHENTIK_POSTGRESQL__USER=authentik
      - AUTHENTIK_POSTGRESQL__NAME=authentik
      - AUTHENTIK_POSTGRESQL__PASSWORD=${AUTHENTIK_PG_PASS:-changeme}
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}
    volumes:
      - authentik-media:/media
      - authentik-templates:/templates
    ports:
      - "${AUTHENTIK_PORT_HTTP:-9000}:9000"
      - "${AUTHENTIK_PORT_HTTPS:-9443}:9443"
    depends_on:
      - authentik-postgresql
      - authentik-redis
    networks:
      - media-network
    profiles:
      - auth

  authentik-worker:
    image: ghcr.io/goauthentik/server:latest
    container_name: authentik-worker
    restart: unless-stopped
    command: worker
    environment:
      - AUTHENTIK_REDIS__HOST=authentik-redis
      - AUTHENTIK_POSTGRESQL__HOST=authentik-postgresql
      - AUTHENTIK_POSTGRESQL__USER=authentik
      - AUTHENTIK_POSTGRESQL__NAME=authentik
      - AUTHENTIK_POSTGRESQL__PASSWORD=${AUTHENTIK_PG_PASS:-changeme}
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}
    volumes:
      - authentik-media:/media
      - authentik-templates:/templates
      - authentik-certs:/certs
    depends_on:
      - authentik-postgresql
      - authentik-redis
    networks:
      - media-network
    profiles:
      - auth

  # Tdarr - Media Transcoding
  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
    container_name: tdarr
    restart: unless-stopped
    ports:
      - "${TDARR_SERVER_PORT:-8266}:8266"
      - "${TDARR_WEBUI_PORT:-8265}:8265"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/Los_Angeles}
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - nodeID=MainNode
    volumes:
      - tdarr-server:/app/server
      - tdarr-configs:/app/configs
      - tdarr-logs:/app/logs
      - ${MEDIA_PATH}:/media
      - ${TDARR_TRANSCODE_CACHE:-/tmp/tdarr}:/temp
    networks:
      - media-network
    profiles:
      - transcoding

volumes:
  traefik-letsencrypt:
  heimdall-config:
  homepage-config:
  authentik-database:
  authentik-redis:
  authentik-media:
  authentik-templates:
  authentik-certs:
  tdarr-server:
  tdarr-configs:
  tdarr-logs:

networks:
  media-network:
    external: true
